import Head from "next/head";
import { ChevronDownIcon } from "@heroicons/react/24/outline";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Online Store - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid gap-4 md:grid-cols-12 md:grid-rows-2 bg-gray-100">
          <div className="hidden md:block md:row-span-2 md:col-span-3">
            {/* category */}
            <div className="bg-white rounded-3xl">
              {/* accordian header */}
              <div className="flex items-center justify-between">
                <span>دسته بندی مقالات</span>
                <ChevronDownIcon className="w-6 h-6 stroke-orange-400" />
              </div>
              {/* accordian content */}
              <div className="">
                <Link href="#" className="block py-2 mb-1">
                  همه مقالات
                </Link>
                <Link href="#" className="block py-2 mb-1">
                  ریکت
                </Link>
                <Link href="#" className="block py-2">
                  جاوااسکریپ
                </Link>
              </div>
            </div>
          </div>
          <div className="bg-blue-200 hidden md:block md:col-span-9">
            sort desktop
          </div>
          <div className="bg-blue-200 md:col-span-9">blogs</div>
        </div>
      </main>
    </>
  );
}
