import Head from "next/head";
import {
  AdjustmentsVerticalIcon,
  ChevronDownIcon,
} from "@heroicons/react/24/outline";
import Link from "next/link";
import { useState } from "react";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Online Store - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-50">
        <div className="container mx-auto lg:max-w-screen-xl">
          <div className="grid gap-8 md:grid-cols-12 md:grid-rows-[60px_minmax(300px,_1fr)]  min-h-screen">
            {/* category desktop */}
            <div className="hidden md:block md:row-span-2 md:col-span-3">
              <div className="bg-white rounded-3xl overflow-hidden">
                {/* accordian header */}
                <div
                  className="flex items-center justify-between py-4 px-4 cursor-pointer bg-purple-200"
                  onClick={() => setIsOpen(!isOpen)}
                >
                  <span>دسته بندی مقالات</span>
                  <ChevronDownIcon
                    className={`w-6 h-6 stroke-purple-400 transition-all duration-200 ${
                      isOpen ? "rotate-180" : "rotate-0"
                    }`}
                  />
                </div>
                {/* accordian content */}
                <div className={` ${isOpen ? "block" : "hidden"}`}>
                  <Link
                    href="#"
                    className="block py-2 hover:bg-purple-50 pr-4 mb-1"
                  >
                    همه مقالات
                  </Link>
                  <Link
                    href="#"
                    className="block py-2 hover:bg-purple-50 pr-4 mb-1"
                  >
                    ریکت
                  </Link>
                  <Link href="#" className="block py-2 hover:bg-purple-50 pr-4">
                    جاوااسکریپ
                  </Link>
                </div>
              </div>
            </div>
            {/* sortbar desktop */}
            <div className="hidden md:block md:col-span-9">
              <div className="bg-white rounded-3xl px-4 flex items-center">
                <div className="flex gap-x-2 items-center ml-4">
                  <AdjustmentsVerticalIcon className="w-6 h-6" />
                  <span className="text-gray-700">مرتب سازی :</span>
                </div>
                <ul className="flex items-center gap-x-4">
                  <li className="py-4 cursor-pointer text-gray-700">
                    پر بازدیدترین
                  </li>
                  <li className="py-4 cursor-pointer text-gray-700">
                    محبوب ترین
                  </li>
                  <li className="py-4 cursor-pointer text-gray-700">
                    جدیدترین
                  </li>
                </ul>
              </div>
            </div>
            {/* blogs section */}
            <div className="md:col-span-9 grid grid-cols-6 gap-8">
              {[
                "node.png",
                "next.jpeg",
                "vue.png",
                "nuxt.png",
                "node.png",
                "next.jpeg",
              ].map((item, index) => {
                return (
                  <div
                    key={index}
                    className="col-span-6 md:col-span-3 lg:col-span-2 rounded-3xl p-2"
                  >
                    {/* cover image */}
                    <div className="aspect-w-16 aspect-h-9">
                      <img
                        src={`/images/${item}`}
                        alt=""
                        className="rounded-2xl w-full h-full object-center object-cover"
                      />
                    </div>
                    {/* blog content */}
                    <div className="bg-gray-50 rounded-2xl">
                      <h2 className="mb-4 font-bold">
                        بررسی کامل ریکت و ریداکس
                      </h2>
                      <div className="flex justify-between items-center">
                        <div className="flex items-center">
                          <img
                            src="/images/next.jpeg"
                            alt=""
                            className="w-6 h-6 rounded-full ring-2 ring-white ml-2"
                          />
                          <span className="text-sm">سپیده بیگلری زاده</span>
                        </div>
                        <span className="text-xs px-2 py-1 rounded-xl bg-blue-100 text-blue-600 hover:text-blue-100 hover:bg-blue-600 transition-all duration-300 cursor-pointer">
                          ری اکت
                        </span>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
